services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      - --providers.file.filename=/etc/traefik/dynamic/tls.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./certs:/certs:ro
    restart: unless-stopped

  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: portifolio:latest
    container_name: portfolio
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio.rule=Host(`pavas.dev.br`) || Host(`www.pavas.dev.br`)
      - traefik.http.routers.portfolio.entrypoints=websecure
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.services.portfolio.loadbalancer.server.port=8080
